### ISSUE TITLE
Dont cast unnecessarily and pull db twice

### ISSUE THREAD

**Issue by TheKingDave** [bbulis-tgm/tempReader_backend#2]
https://github.com/bbulis-tgm/tempReader_backend/blob/664a35e91da940d203dd2ed0c60cef733e298d8b/src/main/java/com/bulis/temp/backend/model/TeperatureController.java#L31-L35

You are casting unnecessarily. Use this instead:
```java
Iterable<Temperature> temperatures = temperatureReposiroty.findAll();
if (!temperatures.iterator().hasNext()) {
```
Does the same, but more efficient.

Also dont pull the db twice, do this:
```java
return new Response(true, temperatures);
```

(Could also provide pull request if I got the rights)

**Comment by bbulis-tgm** [comment]
fixed issues with pull request in commit #3
